# Build matrix / environment variables are explained on:
# https://www.appveyor.com/docs/appveyor-yml/
# This file can be validated on: https://ci.appveyor.com/tools/validate-yaml

version: "{build}"

environment:
  matrix:
    # AppVeyor currently has no custom job name feature.
    # http://help.appveyor.com/discussions/questions/1623-can-i-provide-a-friendly-name-for-jobs
    - JOB: CMake Visual Studio 2017
      BUILD_SYSTEM: cmake
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_GENERATOR: Visual Studio 15 2017
    - JOB: CMake Visual Studio 2015
      BUILD_SYSTEM: cmake
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CMAKE_GENERATOR: Visual Studio 14 2015
    - JOB: Bazel Visual Studio 2017
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      BUILD_SYSTEM: bazel
      CMAKE_GENERATOR: _

platform:
  - x86
  - x64

configuration:
  - RelWithDebInfo
  - Debug

matrix:
  exclude:
  - BUILD_SYSTEM: cmake  # TODO(pwnall): Remove when done iterating.
  - configuration: Debug
    BUILD_SYSTEM: bazel
  - platform: x86
    BUILD_SYSTEM: bazel

install:
  - appveyor DownloadFile https://github.com/bazelbuild/bazel/releases/download/0.7.0/bazel-0.7.0-windows-x86_64.exe -FileName bazel.exe

build:
  verbosity: minimal

build_script:
  - git submodule update --init --recursive

  - if "%BUILD_SYSTEM%"=="cmake" ( mkdir build )
  - if "%BUILD_SYSTEM%"=="cmake" ( cd build )
  - if "%platform%"=="x64" ( set CMAKE_GENERATOR=%CMAKE_GENERATOR% Win64 )
  - if "%BUILD_SYSTEM%"=="cmake" ( cmake --version )
  - if "%BUILD_SYSTEM%"=="cmake" ( cmake .. -G "%CMAKE_GENERATOR%"
        -DCMAKE_CONFIGURATION_TYPES="%CONFIGURATION%" )
  - if "%BUILD_SYSTEM%"=="cmake" ( cmake --build . --config %CONFIGURATION% )
  - if "%BUILD_SYSTEM%"=="cmake" ( cd .. )

  - if "%BUILD_SYSTEM%"=="bazel" ( bazel --batch build -c opt //... )

test_script:
  - if "%BUILD_SYSTEM%"=="cmake" ( out\%CONFIGURATION%\snappy_unittest )
  - if "%BUILD_SYSTEM%"=="bazel" ( bazel --batch test -c opt
      --test_output streamed //... )
